### ISSUE TITLE
Example external CMake project fails to build

### ISSUE THREAD

**Issue by sisaha9** [PointOneNav/fusion-engine-client#182]
Here are the steps I followed
```bash
git clone https://github.com/PointOneNav/fusion-engine-client.git
mv fusion-engine-client/examples/external_cmake_project/ .
rm -rf fusion-engine-client
cd external_cmake_project
mkdir build
cd build
cmake ..
make
```

At `make` it fails with the following error

```bash
external_cmake_project/main.cc:14:10: fatal error: point_one/fusion_engine/messages/core.h: No such file or directory
```

**Comment by adamshapiro0** [comment]
Hey @sisaha9 thanks for pointing that out. The CMake file for that example should have been pointing to 1.16.0, not 1.15.2. The changes to support FetchContent were added in 1.16.0 (as was this example itself).

I just pushed a PR to fix it. Will merge shortly.
